version: 0.2
env:
  variables:
    TEMPLATE_BUCKET: "output-templates"
phases:
  build:
    commands:
      - cat infra.yml
      - aws cloudformation package --template ./infra.yaml --s3-bucket $TEMPLATE_BUCKET --output-template-file packaged-root-template.yaml
artifacts:
  files:
    - 'packaged-root-template.yaml'