version: 0.2
phases:
  build:
    commands:
      - cat infra.yml
      - aws cloudformation deploy --template-file infra.yml --stack-name pipeinfra
artifacts:
  files:
    - 'packaged-root-template.yaml'